# Generated by Django 5.0.4 on 2025-04-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rented',
            name='id',
        ),
        migrations.AlterField(
            model_name='rented',
            name='movie_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
